# Generated by Django 4.1.3 on 2023-01-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
