# Generated by Django 4.1.3 on 2023-01-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_delete_abc_remove_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
