# Generated by Django 4.1.3 on 2023-01-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0010_alter_poll_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user_id',
        ),
    ]
